a=input("NAME:")
b=input("SAP ID:")
C=input("DOB:")
d=input("ADDRESS")
e=input("PROGRAMME")
f=input("SEMESTER")
print("NAME:",a)
print("SAP ID:",b)
print("DATE OF BIRTH:",c)
print("ADDRESS:",d)
print("PROGRAMME:",e)
print("SEMESTER:",f)
